### ISSUE TITLE
Filtrar los acuerdos marcos para su análisis

### ISSUE THREAD

**Issue by dcabo** [civio/boe#11]
¿Cómo los distinguimos? Pensábamos que no tendrían importe, pero hay muchos que sí tienen, como [éste](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-74) o [éste](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-1400). Hay otros que no lo tienen, como [éste](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-904), pero tal vez por ser un contrato por unidades (y sí que tiene valor estimado, por ejemplo). También [los hay](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-16801) sin ningún tipo de importe. Lo más coherente parece ser buscar simplemente la frase "acuerdo marco" en el título.

**Comment by dcabo** [comment]
¿Cómo de relevantes son entre los anuncios de tipo "Obras"? En 2015 sólo aparecen 6 (más uno sin Tipo, que tendríamos que mirar por si acaso). Son los siguientes:

* [BOE-B-2015-3203](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-3203)
* [BOE-B-2015-8746](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-8746)
* [BOE-B-2015-9263](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-9263)
* [BOE-B-2015-24407](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-24407)
* [BOE-B-2015-30354](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-30354)
* [BOE-B-2015-30355](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-30355)
* [BOE-B-2015-36378](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-36378)

@EvaBelmonte tiene que revisarlos.

**Comment by dcabo** [comment]
Hay acuerdos marco (AM) sin la frase "acuerdo marco" en el título, como [éste](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-6045). Sí que aparece en el texto, dentro de "Objeto del contrato" y de "Tramitación y Procedimiento".

En 2015 la propiedad "Objeto del contrato - Acuerdo marco" parece bastante fiable, pero no 100%: encontramos seis anuncios que no mencionan AM en el título y no tienen ésta propiedad. Cinco de ellos dicen que son AM en el Procedimiento, pero [uno de ellos](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-2615) solo sabemos que lo es porque lo dicen las observaciones del Análisis, nada más.

Tal vez deberíamos buscar la frase "acuerdo marco" en todo el anuncio, si es que realmente necesitamos distinguir los AM del resto.

**Comment by EvaBelmonte** [comment]
Entonces, ¿buscamos por la frase "acuerdo marco" y miro sobre eso, o quieres que mire ya esos 7 que me pasas?

**Comment by dcabo** [comment]
Sí, la idea es buscar la frase "acuerdo marco" en todo el anuncio.

Pero, ¿tu quieres revisarlos uno a uno? ¿Aunque tengan precio y parezca que pueden pasar como un contrato más?

**Comment by EvaBelmonte** [comment]
Que tengan precio no significa que los podamos pasar como un contrato más. Los acuerdos marco son contratos en los que se dice: os podemos comprar esto. Pero no son adjudicaciones. El problema es que las adjudicaciones derivadas de acuerdos marco (que sí podemos sumar) no se publican en la mayoría de casos.

Por lo tanto, sumarlos al resto sería erróneo. Creo que la única opción es que los compruebe y lo valore, pero casi 100% seguro vamos a tener que eliminarlos.

**Comment by EvaBelmonte** [comment]
Con los datos de 2015 ya podemos tomar una decisión definitiva sobre acuerdos marco:

- Tu columna saca 19 acuerdos marcos: sí. De esos, 6 sí son acuerdos marco. 
- En objeto del contrato-acuerdo marco salen 4.
- En Análisis-Observaciones salen 5.
- De los 7 que comentabas al principio de este issue, son todos menos BOE-B-2015-8746, que no es contrato de obras. 

Conclusiones:

- La mejor manera de asegurarnos que cogemos todos los acuerdos marco es que saques esa columna y yo revise a mano sobre eso. No es difícil, hay pocos acuerdos marco de obra.

- Vamos a dejarlos fuera de la base de datos principal, puesto que no son adjudicaciones y no podemos sumarlos al resto. Porque 1) no son contratos firmados y pagados, sino planes de contratación; 2) los precios de adjudicación a veces son totales que no tienen por qué pagarse o precios unitarios, lo que hace imposible sumarlos al resto. Eso sí, como pueden ser interesantes, vamos a añadirlos al archivo de "concesiones" en una pestaña aparte para analizarlos cuando miremos las concesiones.
