### ISSUE TITLE
Incorporar correcciones y contratos mal clasificados

### ISSUE THREAD

**Issue by dcabo** [civio/boe#9]
Revisando los anuncios descartados en 2015 hemos encontrado uno mal clasificado (aparece como 'Otros' cuando es una formalización) que sí debemos incluir:

[Resolución de la Autoridad Portuaria de Huelva por la que se hace publica la formalización del contrato para "Mejora de señalización y protección de los cruces a nivel de la Autoridad Portuaria de Huelva"](http://www.boe.es/buscar/doc.php?id=BOE-B-2015-12681).

Tenemos que pensar cual es la mejor forma de gestionar este tipo de correcciones.

**Comment by dcabo** [comment]
De forma más general, tenemos qué pensar cómo incorporar todas las correcciones que aparezcan durante el proceso de revisión del log.

**Comment by dcabo** [comment]
Me he planteado la opción de hacer un 'diff de ficheros Excel' para simplificar el trabajo de los revisores (principalmente @EvaBelmonte). La idea era convertir el CSV inicial a Excel y guardar una copia en este punto. Más adelante, después de corregir los datos en Excel, podría comparar la versión final con la original y extraer de ahí la lista de celdas modificadas. Es decir, un control de versiones a medida capaz de entender ficheros XLS.

Dos posibles formas de hacer esto:

* Convertir el XLS final a CSV usando el `in2csv` de CSVKit. Pero una primera prueba mostró que un 'roundtrip CSV->XLS->CSV' ya muestra diferencias: decimales '.00' y cadenas de texto vacías `""` que desaparecen. Peor aún, al intentar repetir el ejercicio con el dataset de 2015 el conversor muestra un error (enteros mayores que el rango permitido) y aborta.

* Hacer la comparativa nosotros, celda a celda, usando alguna gema como 'spreadsheet' o 'roo'. Esto es factible, en teoría, pero llegados a este punto parece razonable cuestionarnos si no se nos está yendo la cabeza.

**Comment by dcabo** [comment]
Algunos de los cambios que deseamos realizar se limitan a una celda concreta, fruto de, por ejemplo, una corrección de errores del BOE. Pero otros cambios requiren añadir una nueva adjudicación, como es el caso del anuncio que abre este issue, lo cual implica añadir unas ~30 columnas. Es poco eficiente pedirle al corrector que haga todo el trabajo que ya sabe hacer nuestro parser automático: sería por tanto mejor poder decirle al parser que incluya un anuncio a pesar de no parecer una formalización, por ejemplo; pero, por otro lado, añadir código para cada escenario puntual complicaría mucho el código y el proceso, pues acabaríamos con listas de contratos a incluir -en el parser-, listas de erratas a corregir -sobre el dataset generado-, listas de lotes a incluir -en algún punto posterior-, etc.

La solución más sencilla parece ser incluir todos los cambios posibles en un único punto, y este punto sería el conjunto de ficheros fuente: **vamos a crear versiones corregidas de los XML de partida** cuando sea necesario. Eso sí, para mantener la trazabilidad y poder verificar el proceso en cualquier momento, vamos a convervar al lado el fichero original. Modificaremos el parser para ignorar un fichero original si detectamos que existe una versión corregida.

**Comment by dcabo** [comment]
@EvaBelmonte, ¿me puedes pasar las correcciones de errores que encontraste para 2015?

**Comment by EvaBelmonte** [comment]
Hasta ahora, hemos realizado estos **pasos manuales**:

###Revisar log de los que quedan fuera y blanks. 
Solo añadimos el que comentas al inicio de este issue, si no recuerdo mal.

###Revisar contratos mixtos y ver cuáles pasan.
Hay que incluir SOLO estos:
BOE-B-2015-2207
BOE-B-2015-5573
BOE-B-2015-11532
BOE-B-2015-11535
BOE-B-2015-11536
BOE-B-2015-11537
BOE-B-2015-32491

###Revisar las correcciones de errores. Copio aquí el CSV y adjunto el Excel [Correcciones 2015.xlsx](https://github.com/civio/boe/files/103860/Correcciones.2015.xlsx) porque está puñetero con las tildes:

BOE ID,campo,correcci—n,,url anuncio original
BOE-B-2015-25557,Adjudicaci—n - Contratista,"ARIAS INFRAESTRUCTURAS, S.A.",,http://boe.es/boe/dias/2015/08/11/pdfs/BOE-B-2015-25557.pdf
BOE-B-2015-25557,Formalizaci—n del contrato - Contratista,"ARIAS INFRAESTRUCTURAS, S.A.",,
BOE-B-2015-36548,Formalizaci—n del contrato - Fecha de adjudicaci—n,22 de octubre de 2015,,http://boe.es/boe/dias/2015/12/05/pdfs/BOE-B-2015-36548.pdf
BOE-B-2015-36548,Formalizaci—n del contrato - Fecha de formalizaci—n del contrato,17 de noviembre de 2015,,
BOE-B-2015-36548,Formalizaci—n del contrato - Contratista,"Urcotex Inmobiliaria, S.L.",,
BOE-B-2015-36548,Formalizaci—n del contrato - Importe o canon de adjudicaci—n,"Importe neto: 566.869,28, Importe total: 685.911,83",,

Tengo pendiente: acuerdos marcos/lotes

**Comment by dcabo** [comment]
Hemos visto que en la práctica trabajar únicamente con los XML originales es extremadamente incómodo para los lotes, que pueden corregirse mucho más cómodamente **trabajando directamente en Excel**. Una vez que abrimos esta puerta podemos aprovechar el "punto de intervención" para realizar el resto de operaciones manuales, como aplicar correcciones de errores o excluir contratos de obra mixtos no relevantes. Por comodidad, vamos a generar, además del CSV con todos las adjudicaciones y licitaciones, **un CSV sólo con aquellos anuncios potencialmente relevantes para QCLO** (es decir, tipo "Obras" y "Mixto - Obras").

Eso sí, seguiremos modificando los XML originales para recuperar descartes relevantes. Es decir, tenemos dos puntos de intervención sobre los datos.
